### ISSUE TITLE
Is this still under development? 

### ISSUE THREAD

**Issue by alterx** [ColdSauce/CosmosBrowserAndroid#14]
I know this was created a lot of time ago but you guys got featured today in the "Built by teens" collection of Product Hunt. With that said, is this under active development? I don't see much activity in the last months.

If you dropped the project, what's the reason? Was it not feasible from a technical standpoint?

**Comment by ColdSauce** [comment]
Going to completely re write it from scratch starting tonight!

**Comment by alterx** [comment]
Awesome! 
I'll keep an eye on it.
